language: node_js
script: npm run-script test-travis
node_js:
- '0.10'
- '0.11'
after_script: npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: Sv9ZMPghLbKGg0UW87JwtMouZH33IEHzeJkfy/qJWq7Raz4HCnk3ciY8kTa7zgsEaavMiUga3c0kS6fCkP/oCc1BfKCH93ukL9KQS8+kt2IpSpC7R1tcyBKGHxqjoBwdLmLiNmDnAMufu7rgliIM/y4yq/mO0jPVLZETN9d6alE=
  on:
    repo: wooorm/retext-range
